### ISSUE TITLE
no defauilt HTML export template

### ISSUE THREAD

**Issue by digininja** [securityroots/dradispro-tracker#300]
On my completely fresh install, tried an HTML export, as there are no default templates included it fails with this error:

```
Completed 200 OK in 31.7ms (Views: 20.8ms | ActiveRecord: 1.2ms)
Started POST "/pro/export" for 84.93.78.15 at 2015-09-16 04:03:00 -0400
Processing by ExportController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"3zwe0keM3LXeHKNpsSrIZbC7p/lDMf+h87tf3MHcv9Y=", "plugin"=>"html_export", "route"=>"root", "template"=>""}
Redirected to https://dradispro.local:60443/pro/export/html/
Completed 302 Found in 6.3ms (ActiveRecord: 0.4ms)
Started GET "/pro/export/html/" for 84.93.78.15 at 2015-09-16 04:03:00 -0400
Processing by Dradis::Plugins::HtmlExport::BaseController#index as HTML
Completed 500 Internal Server Error in 268.0ms

Errno::ENOENT (No such file or directory - /opt/dradispro/dradispro/releases/20131126124657/templates/reports/html_export):
  /opt/dradispro/dradispro/current/vendor/cache/dradis-html_export/lib/dradis/plugins/html_export/exporter.rb:59:in `read'
  /opt/dradispro/dradispro/current/vendor/cache/dradis-html_export/lib/dradis/plugins/html_export/exporter.rb:59:in `export'
  vendor/cache/dradis-html_export/app/controllers/dradis/plugins/html_export/base_controller.rb:16:in `index'
  actionpack (3.2.21) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (3.2.21) lib/abstract_controller/base.rb:167:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (3.2.21) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  activesupport (3.2.21) lib/active_support/callbacks.rb:447:in `_run__141914659091825251__process_action__7881161785119825__callbacks'

**Comment by etdsoft** [comment]
If you navigate to Admin > Templates > Reports do you see any files in the HTML Export section?

What about after rebooting the `dradispro-unicorn` service via /setup?

**Comment by etdsoft** [comment]
To give more background, the default report sample is included in the plugin and copied to the app's directory at boot time.

**Comment by digininja** [comment]
No, and the html_export directory doesn't exist on disk. As I've not
rebooted since applying the DUP could that be causing it?
